<?php
namespace Tests\DataBase\Exceptions;

use Veles\DataBase\Exceptions\DbException;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-02-01 at 11:13:18.
 */
class DbExceptionTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var DbException
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $msg = "SQLSTATE[28000] [1045] Access denied for user 'user'@'localhost' (using password: YES)";
        $code = 28000;

        $exception = new \PDOException($msg, $code);
        $this->object = new DbException($msg, $code, $exception);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Veles\DataBase\Exceptions\DbException::getAnsiCode
     */
    public function testGetAnsiCode()
    {
        $expected = '28000';
        $result = $this->object->getAnsiCode();
        $msg = 'DbException::getAnsiCode returns wrong result!';
        $this->assertSame($expected, $result, $msg);
    }

    /**
     * @covers Veles\DataBase\Exceptions\DbException::setAnsiCode
     */
    public function testSetAnsiCode()
    {
        $expected = uniqid();
        $this->object->setAnsiCode($expected);
        $result = $this->object->getAnsiCode();
        $msg = 'DbException::setAnsiCode wrong behavior!';
        $this->assertSame($expected, $result, $msg);
    }
}
