<?php
namespace Tests\Auth;

use Veles\Tests\Auth\UsrAuthCopy;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-12-24 at 16:37:03.
 */
class UsrAuthTest extends \PHPUnit_Framework_TestCase
{
	/**
	 * @var UsrAuth
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp()
	{
		$this->object = UsrAuthCopy::instance();
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown()
	{
	}

	/**
	 * @covers Veles\Auth\UsrAuth::instance
	 * @todo   Implement testInstance().
	 */
	public function testInstance()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Veles\Auth\UsrAuth::getErrors
	 * @todo   Implement testGetErrors().
	 */
	public function testGetErrors()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Veles\Auth\UsrAuth::hasAccess
	 * @todo   Implement testHasAccess().
	 */
	public function testHasAccess()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Veles\Auth\UsrAuth::getUser
	 * @todo   Implement testGetUser().
	 */
	public function testGetUser()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}
}
