<?php
namespace Veles\Tests\Tools;

use Veles\Tools\ModelParams;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-12-07 at 21:23:06.
 * @group tools
 */
class ModelParamsTest extends \PHPUnit_Framework_TestCase
{
	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown()
	{
	}

	/**
	 * @covers       Veles\Tools\ModelParams::getType
	 * @dataProvider getTypeProvider
	 *
	 * @param $type
	 * @param $expected
	 */
	public function testGetType($type, $expected)
	{
		$result = ModelParams::getType($type);
		$msg = 'ModelParams::getType() returns wrong result!';
		$this->assertSame($expected, $result, $msg);
	}

	public function getTypeProvider()
	{
		return [
			['char(20)', 'string'],
			['varchar(20)', 'string'],
			['mediumtext', 'string'],
			['text', 'string'],
			['enum', 'string'],
			['timestamp', 'string'],
			['datetime', 'string'],
			['date', 'string'],
			['time', 'string'],
			['tinyint(10)', 'int'],
			['bit(1)', 'string'],
			['smallint(10)', 'int'],
			['int(10)', 'int'],
			['mediumint(5)', 'int'],
			['bigint(10)', 'int'],
			['decimal(10,0)', 'float'],
			['dec(10,0)', 'float'],
			['float', 'float'],
			['real', 'float'],
			['double', 'float']
		];
	}

	/**
	 * @covers       Veles\Tools\ModelParams::getType
	 * @expectedException \RuntimeException
	 * @expectedExceptionMessage Unknown data type
	 */
	public function testRuntimeException()
	{
		ModelParams::getType('unknown');
	}
}
