<?php
namespace Tests\Tools;

use Veles\Tools\PhpToken;
use Veles\Validators\PhpToken as Validator;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-11-03 at 22:07:03.
 * @group Tools
 */
class PhpTokenTest extends \PHPUnit_Framework_TestCase
{
	/**
	 * @var PhpToken
	 */
	protected $object;
	private static $content = 'this is test content';

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp()
	{
		$validator = new Validator;
		$this->object = new PhpToken(self::$content, $validator);
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown()
	{
	}

	/**
	 * @covers Veles\Tools\PhpToken::setContent
	 * @todo   Implement testSetContent().
	 */
	public function testSetContent()
	{
		$msg = 'Wrong initial value of PhpToken::content';
		$this->assertAttributeSame(self::$content, 'content', $this->object, $msg);

		$expected = uniqid();
		$this->object->setContent($expected);

		$msg = 'Wrong behavior of PhpToken::setContent()';
		$this->assertAttributeSame($expected, 'content', $this->object, $msg);
	}

	/**
	 * @covers Veles\Tools\PhpToken::getContent
	 * @todo   Implement testGetContent().
	 */
	public function testGetContent()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Veles\Tools\PhpToken::setId
	 * @todo   Implement testSetId().
	 */
	public function testSetId()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Veles\Tools\PhpToken::getId
	 * @todo   Implement testGetId().
	 */
	public function testGetId()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Veles\Tools\PhpToken::setLine
	 * @todo   Implement testSetLine().
	 */
	public function testSetLine()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Veles\Tools\PhpToken::getLine
	 * @todo   Implement testGetLine().
	 */
	public function testGetLine()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Veles\Tools\PhpToken::setName
	 * @todo   Implement testSetName().
	 */
	public function testSetName()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Veles\Tools\PhpToken::getName
	 * @todo   Implement testGetName().
	 */
	public function testGetName()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}
}
