<?php
namespace Veles\Tests\Tools;

use Veles\Tools\PhpTokenBase;
use Veles\Validators\PhpTokenValidator;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-11-03 at 22:07:03.
 * @group tools
 */
class PhpTokenBaseTest extends \PHPUnit_Framework_TestCase
{
	/**
	 * @var PhpTokenBase
	 */
	protected $object;
	private static $content = 'this is test content';

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp()
	{
		$validator = new PhpTokenValidator;
		$this->object = new PhpTokenBase(self::$content, $validator);
	}

	/**
	 * @covers Veles\Tools\PhpTokenBase::__construct
	 * @dataProvider constructProvider
	 * @param $token
	 * @param $validator
	 * @param $expected
	 */
	public function testConstruct($token, $validator, $expected)
	{
		$obj = new PhpTokenBase($token, $validator);

		$msg = 'Wrong PhpTokenBase::identifier property value';
		$this->assertAttributeSame($expected[0], 'identifier', $obj, $msg);

		$msg = 'Wrong PhpTokenBase::content property value';
		$this->assertAttributeSame($expected[1], 'content', $obj, $msg);

		$msg = 'Wrong PhpTokenBase::line property value';
		$this->assertAttributeSame($expected[2], 'line', $obj, $msg);
	}

	/**
	 * @return array
	 */
	public function constructProvider()
	{
		$validator = new PhpTokenValidator;

		$token_string = uniqid();
		$token_array = [mt_rand(1, 300), uniqid(), mt_rand()];

		return [
			[
				$token_array,
				$validator,
				$token_array
			],
			[
				$token_string,
				$validator,
				[0, $token_string, 0]
			]
		];
	}

	/**
	 * @expectedException \Exception
	 * @dataProvider constructExceptionProvider
	 * @param $not_valid_token
	 * @param $validator
	 */
	public function testConstructException($not_valid_token, $validator)
	{
		$obj = new PhpTokenBase($not_valid_token, $validator);
	}

	public function constructExceptionProvider()
	{
		return [[mt_rand(), new PhpTokenValidator]];
	}

	/**
	 * @covers Veles\Tools\PhpToken::setContent
	 */
	public function testSetContent()
	{
		$msg = 'Wrong initial value of PhpTokenBase::content';
		$this->assertAttributeSame(self::$content, 'content', $this->object, $msg);

		$expected = uniqid();
		$this->object->setContent($expected);

		$msg = 'Wrong behavior of PhpTokenBase::setContent()';
		$this->assertAttributeSame($expected, 'content', $this->object, $msg);
	}

	/**
	 * @covers Veles\Tools\PhpTokenBase::getContent
	 */
	public function testGetContent()
	{
		$expected = uniqid();
		$this->object->setContent($expected);

		$result = $this->object->getContent();

		$msg = 'Wrong behavior of PhpTokenBase::getContent()';
		$this->assertSame($expected, $result, $msg);
	}

	/**
	 * @covers Veles\Tools\PhpTokenBase::setId
	 */
	public function testSetId()
	{
		$expected = mt_rand();
		$this->object->setId($expected);

		$msg = 'Wrong behavior of PhpTokenBase::setId()';
		$this->assertAttributeSame($expected, 'identifier', $this->object, $msg);
	}

	/**
	 * @covers Veles\Tools\PhpTokenBase::getId
	 */
	public function testGetId()
	{
		$expected = mt_rand();
		$this->object->setId($expected);

		$result = $this->object->getId();

		$msg = 'Wrong behavior of PhpTokenBase::getId()';
		$this->assertSame($expected, $result, $msg);
	}

	/**
	 * @covers Veles\Tools\PhpTokenBase::setLine
	 */
	public function testSetLine()
	{
		$expected = mt_rand();
		$this->object->setLine($expected);

		$msg = 'Wrong behavior of PhpTokenBase::setLine()';
		$this->assertAttributeSame($expected, 'line', $this->object, $msg);
	}

	/**
	 * @covers Veles\Tools\PhpTokenBase::getLine
	 */
	public function testGetLine()
	{
		$expected = mt_rand();
		$this->object->setLine($expected);

		$result = $this->object->getLine();

		$msg = 'Wrong behavior of PhpTokenBase::getLine()';
		$this->assertSame($expected, $result, $msg);
	}
}
