<?php
namespace Veles\Tests\Tools;

use Veles\Tools\SnippetBuilder;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-08-17 at 18:34:34.
 * @group tools
 */
class SnippetBuilderTest extends \PHPUnit_Framework_TestCase
{
	/**
	 * @var SnippetBuilder
	 */
	protected $object;

	/**
	 * @covers Veles\Tools\SnippetBuilder::__construct()
	 */
	public function testConstruct()
	{
		$expected = [
			'var1' => 'value1',
			'var2' => 'value2',
			'var3' => 'value3'
		];

		$obj = new SnippetBuilder($expected);
		$msg = 'SnippetBuilder::__construct() wrong behavior!';
		$this->assertAttributeEquals($expected, 'variables', $obj, $msg);

		$class = new \stdClass;
		$class->var1 = 'value1';
		$class->var2 = 'value2';
		$class->var3 = 'value3';

		$obj = new SnippetBuilder($class);
		$msg = 'SnippetBuilder::__construct() wrong behavior!';
		$this->assertAttributeEquals($expected, 'variables', $obj, $msg);
	}

	/**
	 * @covers Veles\Tools\SnippetBuilder::build
	 */
	public function testBuild()
	{
		$expected = <<<EOF
<!DOCTYPE html>
<html>
<head>
	<title>Veles is a fast PHP framework</title>
</head>
<body>
	<div id="main_wrapper">
		Test complete!
	</div>
	<div id="footer_wrapper">
		Hello World!
	</div>
</body>
</html>

EOF;

		$vars = ['a' => 'Test', 'b' => 'complete', 'c' => 'Hello'];
		$obj = new SnippetBuilder($vars);
		$path = realpath(__DIR__ . '/../Project/View/Frontend/index.phtml');
		$result = $obj->build($path);

		$msg = 'SnippetBuilder::build() returns wrong result!';
		$this->assertSame($expected, $result, $msg);
	}
}
