<?php
namespace Veles\Tests\DataBase;

use Veles\DataBase\DbPaginator;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-12-27 at 18:28:23.
 */
class DbPaginatorTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var DbPaginator
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new DbPaginator;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Veles\DataBase\DbPaginator::__toString
     * @todo   Implement test__toString().
     */
    public function test__toString()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Veles\DataBase\DbPaginator::getOffset
     * @todo   Implement testGetOffset().
     */
    public function testGetOffset()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Veles\DataBase\DbPaginator::getLimit
     * @todo   Implement testGetLimit().
     */
    public function testGetLimit()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Veles\DataBase\DbPaginator::setLimit
     * @todo   Implement testSetLimit().
     */
    public function testSetLimit()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Veles\DataBase\DbPaginator::getSqlLimit
     * @todo   Implement testGetSqlLimit().
     */
    public function testGetSqlLimit()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Veles\DataBase\DbPaginator::getMaxPages
     * @todo   Implement testGetMaxPages().
     */
    public function testGetMaxPages()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Veles\DataBase\DbPaginator::calcMaxPages
     * @todo   Implement testCalcMaxPages().
     */
    public function testCalcMaxPages()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Veles\DataBase\DbPaginator::getCurrPage
     * @todo   Implement testGetCurrPage().
     */
    public function testGetCurrPage()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
