<?php
namespace Veles\Tests\DataBase;

use Veles\DataBase\Adapters\iDbAdapter;
use Exception;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-12-11 at 15:34:36.
 * @group db
 */
class DbTest extends \PHPUnit_Framework_TestCase
{
	/**
	 * @var Db
	 */
	protected $object;

	protected static $tbl_name;

	public static function setUpBeforeClass()
	{
		// Создаём тестовую таблицу в базе
		$tbl_name = static::$tbl_name = 'rbk_unit_test' . mt_rand(1000, 9999);

		Db::setAdapter('Pdo');
		Db::query("
			CREATE TABLE IF NOT EXISTS $tbl_name (
				id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
				txt CHAR(50) NOT NULL DEFAULT ''
			) ENGINE INNODB
		");

		$arr = array();
		$i = 0;
		while (++$i <= 10) {
			$arr[] = 'test-value';
		}

		$values = implode("'),('", $arr);
		Db::query("INSERT INTO $tbl_name (txt) VALUES ('$values')");
	}

	public static function tearDownAfterClass()
	{
		Db::query('DROP DATABASE ' . static::$tbl_name);
	}

	/**
	 * @covers Veles\DataBase\Db::setAdapter
	 */
	public function testSetAdapter()
	{
		$expected = '\\Veles\\DataBase\\Adapters\\PdoAdapter';
		Db::setAdapter();

		$msg = 'Wrong Db::$adapter_name property value!';
		$this->assertAttributeEquals(
			$expected, 'adapter_name', 'Veles\Tests\DataBase\Db', $msg
		);

		$msg = 'Wrong Db::$adapter property value!';
		$this->assertAttributeEquals(
			null, 'adapter', 'Veles\Tests\DataBase\Db', $msg
		);

		$expected = '\\Veles\\DataBase\\Adapters\\NewAdapter';
		Db::setAdapter('New');

		$msg = 'Wrong Db::$adapter_name property value!';
		$this->assertAttributeEquals(
			$expected, 'adapter_name', 'Veles\Tests\DataBase\Db', $msg
		);

		$msg = 'Wrong Db::$adapter property value!';
		$this->assertAttributeEquals(
			null, 'adapter', 'Veles\Tests\DataBase\Db', $msg
		);

		Db::setAdapter();
	}

	/**
	 * @covers Veles\DataBase\Db::getAdapter
	 */
	public function testGetAdapter()
	{
		Db::unsetAdapter();
		Db::setAdapter();

		$result = Db::getAdapter();
		$this->assertTrue($result instanceof iDbAdapter);

		$result = Db::getAdapter();
		$this->assertTrue($result instanceof iDbAdapter);
	}

	/**
	 * @covers Veles\DataBase\Db::getAdapter
	 * @expectedException Exception
	 * @expectedExceptionMessage Adapter not set!
	 */
	public function testGetAdapterException()
	{
		Db::unsetAdapter();
		Db::getAdapter();
	}

	/**
	 * @covers Veles\DataBase\Db::connection
	 */
	public function testConnection()
	{
		$expected = 'master';

		$this->assertAttributeEquals(
			$expected,
			'connection_name',
			'\Veles\DataBase\Adapters\PdoAdapter',
			'Wrong Db::connection() behavior'
		);

		Db::setAdapter();
		Db::connection($expected);

		$this->assertAttributeEquals(
			$expected,
			'connection_name',
			'\Veles\DataBase\Adapters\PdoAdapter',
			'Wrong Db::connection() behavior'
		);
	}

	/**
	 * @covers Veles\DataBase\Db::value
	 */
	public function testValue()
	{
		Db::setAdapter();
		$expected = (string) mt_rand();
		$result = Db::value("SELECT $expected, 2, 3");

		$msg = 'Wrong Db::value() result';
		$this->assertSame($expected, $result, $msg);
	}

	/**
	 * @covers Veles\DataBase\Db::row
	 */
	public function testRow()
	{
		$tbl_name = static::$tbl_name;
		$expected = array('id' => '1', 'txt' => 'test-value');
		$result = Db::row("
			SELECT * FROM $tbl_name LIMIT 3
		");

		$msg = 'Wrong Db::row() result';
		$this->assertSame($expected, $result, $msg);
	}

	/**
	 * @covers Veles\DataBase\Db::rows
	 */
	public function testRows()
	{
		$tbl_name = static::$tbl_name;
		$expected = array(
			array('id' => '1', 'txt' => 'test-value'),
			array('id' => '2', 'txt' => 'test-value'),
			array('id' => '3', 'txt' => 'test-value'),
		);
		$result = Db::rows("
			SELECT * FROM $tbl_name LIMIT 3
		");

		$msg = 'Wrong Db::rows() result';
		$this->assertSame($expected, $result, $msg);
	}

	/**
	 * @covers Veles\DataBase\Db::begin
	 * @covers Veles\DataBase\Db::rollback
	 * @covers Veles\DataBase\Db::commit
	 */
	public function testTransactions()
	{
		$tbl_name = static::$tbl_name;
		$expected = array('id' => '222', 'txt' => 'test-value');

		Db::begin();
		Db::query("
			INSERT $tbl_name VALUES (222, 'test-value')
		");
		Db::commit();
		$result = Db::row("
			SELECT * FROM $tbl_name WHERE id = 222
		");

		$msg = 'Wrong Db::transaction() test result';
		$this->assertSame($expected, $result, $msg);

		$expected = false;
		Db::begin();
		Db::query("
			INSERT $tbl_name VALUES (333, 'test-value')
		");
		Db::rollback();
		$result = Db::row("
			SELECT * FROM $tbl_name WHERE id = 333
		");

		$this->assertSame($expected, $result, $msg);
	}

	/**
	 * @covers Veles\DataBase\Db::query
	 */
	public function testQuery()
	{
		$tbl_name = static::$tbl_name;
		$expected = true;
		$result = Db::query("
			DELETE FROM $tbl_name WHERE id > :id
		", array(':id' => 8));

		$msg = 'Wrong Db::query result';
		$this->assertSame($expected, $result, $msg);
	}

	/**
	 * @covers Veles\DataBase\Db::getLastInsertId
	 */
	public function testGetLastInsertId()
	{
		$tbl_name = static::$tbl_name;
		$expected = 11;

		Db::query("
			INSERT $tbl_name VALUES (11, 'test-value')
		");
		$result = Db::getLastInsertId();

		$msg = 'Wrong Db::getLastInsertId() result';
		$this->assertSame($expected, $result, $msg);
	}

	/**
	 * @covers Veles\DataBase\Db::getFoundRows
	 */
	public function testGetFoundRows()
	{
		$tbl_name = static::$tbl_name;
		$expected = 9;

		Db::query("
			SELECT SQL_CALC_FOUND_ROWS * FROM $tbl_name LIMIT 0, 5
		");
		$result = Db::getFoundRows();

		$msg = 'Wrong Db::getFoundRows() result';
		$this->assertSame($expected, $result, $msg);
	}

	/**
	 * @covers Veles\DataBase\Db::escape
	 */
	public function testEscape()
	{
		$expected = '\'\\\\\\\'\"\'';

		$result = Db::escape("\'\"");

		$msg = 'Wrong Db::escape() result';
		$this->assertSame($expected, $result, $msg);
	}
}
