<?php
namespace Veles\Tests\DataBase\Helpers;

use Veles\DataBase\Helpers\DbObservable;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-01-17 at 10:10:52.
 */
class DbObservableTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var DbObservable
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new DbObservable;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Veles\DataBase\Helpers\DbObservable::getException
     */
    public function testGetException()
    {
        $expected = new \PDOException;
        $this->object->setException($expected);

        $result = $this->object->getException();
        $msg = 'DbObservable::getException() returns wrong result!';
        $this->assertSame($expected, $result, $msg);
    }

    /**
     * @covers Veles\DataBase\Helpers\DbObservable::setException
     */
    public function testSetException()
    {
        $expected = new \PDOException;
        $this->object->setException($expected);
        $msg = 'DbObservable::setException() wrong behavior!';
        $this->assertAttributeSame($expected, 'exception', $this->object, $msg);
    }

    /**
     * @covers Veles\DataBase\Helpers\DbObservable::getSql
     */
    public function testGetSql()
    {
        $expected = 'SELECT * FROM tbl_name';
        $this->object->setSql($expected);
        $result = $this->object->getSql();
        $msg = 'DbObservable::getSql() returns wrong result!';
        $this->assertSame($expected, $result, $msg);
    }

    /**
     * @covers Veles\DataBase\Helpers\DbObservable::setSql
     * @covers Veles\DataBase\Adapters\PdoAdapter::query
     */
    public function testSetSql()
    {
        $expected = 'SELECT * FROM tbl_name';
        $this->object->setSql($expected);
        $msg = 'Wrong behavior of DbObservable::setSql()!';
        $this->assertAttributeSame($expected, 'sql', $this->object, $msg);
    }

    /**
     * @covers Veles\DataBase\Helpers\DbObservable::getParams
     */
    public function testGetParams()
    {
        $expected = [1, 2, 3];
        $this->object->setParams($expected);
        $result = $this->object->getParams();
        $msg = 'DbObservable::getParams() returns wrong result!';
        $this->assertSame($expected, $result, $msg);
    }

    /**
     * @covers Veles\DataBase\Helpers\DbObservable::setParams
     */
    public function testSetParams()
    {
        $expected = [1, 2, 3];
        $this->object->setParams($expected);
        $msg = 'Wrong DbObservable::setParams() behavior!';
        $this->assertAttributeSame($expected, 'params', $this->object, $msg);
    }
}
