<?php
namespace Veles\Tests\Routing\Exceptions;

use Veles\Routing\Exceptions\NotFoundException;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-08-12 at 09:05:52.
 * @group route
 */
class NotFoundExceptionTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var NotFoundException
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new NotFoundException;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    public function testConstruct()
    {
        $result = $this->object->getCode();
		$msg = 'NotFoundException::__construct() wrong behavior!';
		$this->assertSame(0, $result, $msg);
    }
}
