<?php
namespace Veles\Auth\Strategies;

use Veles\Auth\UsrGroup;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-12-25 at 22:56:19.
 * @group auth
 */
class GuestStrategyTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var GuestStrategy
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new GuestStrategy;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Veles\Auth\Strategies\GuestStrategy::identify
     */
    public function testIdentify()
    {
        $expected = false;
        $result = $this->object->identify();
        $msg = 'GuestStrategy::identify() returns wrong result!';
        $this->assertSame($expected, $result, $msg);

        $expected = ['group' => UsrGroup::GUEST];
        $result = ['group' => ''];
        $this->object->getUser()->getProperties($result);
        $msg = 'Wrong GuestStrategy::identify() behavior!';
        $this->assertSame($expected, $result, $msg);
    }
}
