<?php
namespace Veles\Auth\Strategies;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-12-25 at 23:09:50.
 */
class LoginFormStrategyTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var LoginFormStrategy
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new LoginFormStrategy;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Veles\Auth\Strategies\LoginFormStrategy::identify
     * @todo   Implement testIdentify().
     */
    public function testIdentify()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
