<?php
namespace Tests\Validators;

use Veles\Validators\PhpToken;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-11-22 at 23:26:24.
 */
class PhpTokenTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var PhpToken
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new PhpToken;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Veles\Validators\PhpToken::check
	 * @dataProvider checkProvider
     */
    public function testCheck($data, $expected)
    {
        $result = $this->object->check($data);

		$msg = 'PhpToken validator returned wrong result!';
		$this->assertSame($expected, $result, $msg);
    }

	public function checkProvider()
	{
		return [
			['simple string', true],
			[[1, 2, 3], true],
			[[1, 2], false],
			[new \StdClass, false]
		];
	}
}
