<?php
/**
 * RegEx values validator test
 * @file    RegExValidatorTest.php
 *
 * PHP version 5.4+
 *
 * @author  Alexander Yancharuk <alex at itvault dot info>
 * @date    Вск Фев 17 10:48:43 2013
 * @license The BSD 3-Clause License <http://opensource.org/licenses/BSD-3-Clause>.
 */

namespace Veles\Tests\Validators;

use PHPUnit_Framework_TestCase;
use Veles\Validators\RegExValidator;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-05-26 at 09:40:24.
 */
class RegExValidatorTest extends PHPUnit_Framework_TestCase
{
    /**
     * @covers Veles\Validators\RegExValidator::check
	 * @covers Veles\Validators\RegExValidator::__construct
     * @group Validators
	 * @see RegExValidator::check()
	 * @dataProvider checkProvider
     */
    public function testCheck($pattern, $value, $expected)
    {
		$object = new RegExValidator($pattern);

		$msg = 'Wrong value of RegExValidator::pattern';
		$this->assertAttributeSame($pattern, 'pattern', $object, $msg);

		$result = $object->check($value);

		$msg = 'Wrong RegExValidator::check() validation';
		$this->assertSame($expected, $result, $msg);
    }

	public function checkProvider()
	{
		return [
			[
				'/^\/(?:index.html|page\-(\d+)\.html)?$/',
				'/index.html',
				true
			],
			[
				'/^\/(?:index.html|page\-(\d+)\.html)?$/',
				'/page-19.html',
				true
			],
			[
				'/^\/(?:index.html|page\-(\d+)\.html)?$/',
				'/page-1d9.html',
				false
			]
		];
	}

    /**
     * @covers Veles\Validators\RegExValidator::validate
	 * @group Validators
	 * @see RegExValidator::validate()
	 * @dataProvider validateProvider
     */
    public function testValidate($pattern, $value, $expected)
    {
		$result = RegExValidator::validate($pattern, $value);

		$msg = 'Wrong RegExValidator::validate() validation';
		$this->assertSame($expected, $result, $msg);
    }

	public function validateProvider()
	{
		return [
			[
				'/^\/(?:index.html|page\-(\d+)\.html)?$/',
				'/index.html',
				true
			],
			[
				'/^\/(?:index.html|page\-(\d+)\.html)?$/',
				'/page-19.html',
				true
			],
			[
				'/^\/(?:index.html|page\-(\d+)\.html)?$/',
				'/page-1d9.html',
				false
			]
		];
	}
}
