<?php
namespace Veles\Tests\DataBase\ConnectionPools;

use Veles\DataBase\ConnectionPools\ConnectionPool;
use Veles\DataBase\Connections\PdoConnection;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-12-10 at 13:36:51.
 * @group database
 */
class ConnectionPoolTest extends \PHPUnit_Framework_TestCase
{
	/**
	 * @var ConnectionPool
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp()
	{
		$this->object = new ConnectionPool;
	}

	/**
	 * @covers Veles\DataBase\ConnectionPools\ConnectionPool::getDefaultConnectionName
	 */
	public function testGetDefaultConnectionName()
	{
		$expected = 'test-name';
		$conn = new PdoConnection($expected);
		$this->object->addConnection($conn, true);

		$result = $this->object->getDefaultConnectionName();

		$msg = 'Wrong ConnectionPool::getDefaultConnectionName() result';
		$this->assertSame($expected, $result, $msg);
	}

	/**
	 * @covers Veles\DataBase\ConnectionPools\ConnectionPool::addConnection
	 */
	public function testAddConnection()
	{
		$conn = new PdoConnection('some-name');

		$msg = 'Wrong default value of ConnectionPool::$pool';
		$this->assertAttributeEquals(null, 'pool', $this->object, $msg);

		$this->object->addConnection($conn);

		$expected = array('some-name' => $conn);
		$msg = 'Wrong value of ConnectionPool::$pool';
		$this->assertAttributeEquals($expected, 'pool', $this->object, $msg);

		$conn_default = new PdoConnection('default');
		$this->object->addConnection($conn_default, true);

		$expected = array('some-name' => $conn, 'default' => $conn_default);
		$msg = 'Wrong value of ConnectionPool::$pool';
		$this->assertAttributeEquals($expected, 'pool', $this->object, $msg);

		$expected = 'default';
		$msg = 'Wrong value of ConnectionPool::$default_connection_name';
		$this->assertAttributeEquals(
			$expected, 'default_connection_name', $this->object, $msg
		);
	}

	/**
	 * @covers Veles\DataBase\ConnectionPools\ConnectionPool::getConnection
	 * @depends testAddConnection
	 */
	public function testGetConnection()
	{
		$expected = null;

		$result = $this->object->getConnection('some-name');
		$msg = 'Wrong behavior of ConnectionPool::getConnection';
		$this->assertSame($expected, $result, $msg);

		$expected = new PdoConnection('some-name');
		$this->object->addConnection($expected);

		$result = $this->object->getConnection('some-name');
		$msg = 'Wrong behavior of ConnectionPool::getConnection';
		$this->assertSame($expected, $result, $msg);
	}
}
