<?php
/**
 * Юнит-тест для класса Config
 * @file    ConfigTest.php
 *
 * PHP version 5.3.9+
 *
 * @author  Yancharuk Alexander <alex@itvault.info>
 * @date    Втр Янв 22 22:12:23 2013
 * @copyright The BSD 3-Clause License.
 */

namespace Veles\Tests;

use Veles\Config;

use \PHPUnit_Framework_TestCase;

define('ENVIRONMENT', 'development');
define('CONFIG_FILE', __DIR__ . '/Project/settings.ini');

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-01-22 at 22:11:53.
 */
class ConfigTest extends PHPUnit_Framework_TestCase
{
    /**
     * Unit-test for Config::getParams
     * @covers Veles\Config::getParams
     * @dataProvider getParamsProvider
     * @see    Veles\Config
     */
    public function testGetParams($param, $expected)
    {
        $result = Config::getParams($param);

        $msg = 'Config returned wrong params';
        self::assertEquals($expected, $result);
    }

    /**
     * Data-provider for testGetParams
     */
    public function getParamsProvider()
    {
        $php = array (
            'display_errors'  => '1',
            'log_errors'      => '1',
            '' => array(
                'xdebug.cli_color'                => '1',
                'xdebug.var_display_max_children' => '-1',
            )
        );
        $mysql = array(
            'master' => array('host' => 'localhost', 'user' => 'user')
        );
        return array(array('php', $php), array('db', $mysql));
    }
}
