<?php

use \Veles\Password;
use \Veles\Model\User;
use \Veles\Helper;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2012-12-22 at 08:31:29.
 */
class PasswordTest extends PHPUnit_Framework_TestCase
{
    /**
     * @group RootClasses
     * @covers Veles\Password::checkCookieHash
     * @dataProvider checkCookieHashProvider
     */
    public function testCheckCookieHash($user, $cookie_hash, $expected)
    {
        $result = Password::checkCookieHash($user, $cookie_hash);

        $this->assertTrue($expected === $result);
    }

    /**
     * DataProvider for PasswordTest::testCheckCookieHash
     */
    public function checkCookieHashProvider()
    {
        $user = new User;
        $user->hash = crypt('password', '$2a$07$' . Helper::genStr() . '$');

        return array(
            array($user, $user->getCookieHash(), true),
            array($user, 'wronghash', false)
        );
    }

    /**
     * @group RootClasses
     * @covers Veles\Password::check
     * @dataProvider checkProvider
     */
    public function testCheck($user, $password, $expected)
    {
        $result = Password::check($user, $password);

        $this->assertTrue($expected === $result);
    }

    /**
     * DataProvider for PasswordTest::testCheck
     */
    public function checkProvider()
    {
        $user = new User;
        $user->hash = crypt('password', '$2a$07$' . Helper::genStr() . '$');

        return array(
            array($user, 'password', true),
            array($user, 'wrongpassword', false)
        );
    }
}
