<?php
/**
 * Юнит-тест для класса Helper
 * @file    HelperTest.php
 *
 * PHP version 5.3.9+
 *
 * @author  Yancharuk Alexander <alex@itvault.info>
 * @date    Вск Янв 20 15:25:01 2013
 * @copyright The BSD 3-Clause License.
 */

namespace Veles\Tests;

use \Veles\WebApplication;
use \Veles\View;
use \Veles\Routing\Route;
use \PHPUnit_Framework_TestCase;

if (!defined('ENVIRONMENT')) {
    define('ENVIRONMENT', 'development');
}

if (!defined('CONFIG_FILE')) {
    define('CONFIG_FILE', __DIR__ . '/Project/settings.ini');
}

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-01-22 at 22:53:39.
 */
class WebApplicationTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var View
     */
    protected $view;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->view = new View;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        $this->view->del(array('a', 'b', 'c'));
    }

    /**
     * Unit-test for Application::run
     * @covers Veles\Application::run
     * @dataProvider runProvider
     */
    public function testRun($url, $expected)
    {
        $_SERVER['REQUEST_URI'] = $url;
        $this->expectOutputString($expected['output']);

        WebApplication::run();

        $route  = Route::instance();
        $result = $route->getMap();

        $msg = "Wrong Route::map in $url";
        $this->assertSame($expected['map'], $result, $msg);
    }

    /**
     * DataProvider for Application::run
     */
    public function runProvider()
    {
        $uri      = '/page-2.html';
        $expected = array(
            'map'    => array('page' => '2'),
            'output' => <<<EOF
<!DOCTYPE html>
<html>
<head>
    <title>Veles is a fast PHP framework</title>
</head>
<body>
    <div id="main_wrapper">
        Test complete!
    </div>
    <div id="main_wrapper">
        Hello World!
    </div>
</body>
</html>

EOF
        );

        return array(array($uri, $expected));
    }
}
