<?php
namespace Tests\View\Adapters;

use Veles\View\Adapters\JsonAdapter;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-01-16 at 22:44:11.
 */
class JsonAdapterTest extends \PHPUnit_Framework_TestCase
{
	/**
	 * @var JsonAdapter
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp()
	{
		$this->object = new JsonAdapter;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown()
	{
	}

	/**
	 * @covers Veles\View\Adapters\JsonAdapter::show
	 */
	public function testShow()
	{
		$this->expectOutputString('');
		$this->object->show(null);

		$vars = ['a', 'b', 'c'];

		$this->object->set($vars);
		$expected = json_encode($vars);
		$this->expectOutputString($expected);
		$this->object->show(null);
	}

	/**
	 * @covers Veles\View\Adapters\JsonAdapter::get
	 * @todo   Implement testGet().
	 */
	public function testGet()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Veles\View\Adapters\JsonAdapter::isCached
	 * @todo   Implement testIsCached().
	 */
	public function testIsCached()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}
}
