<?php
namespace Tests\View\Adapters;

use Veles\View\Adapters\NativeAdapter;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-12-20 at 17:47:01.
 * @group View
 */
class NativeAdapterTest extends \PHPUnit_Framework_TestCase
{
	/**
	 * @var NativeAdapter
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp()
	{
		$this->object = new NativeAdapter;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown()
	{
	}

	/**
	 * @covers Veles\View\Adapters\NativeAdapter::setTemplateDir
	 */
	public function testSetTemplateDir()
	{
		$expected = '/templates/dir';
		NativeAdapter::setTemplateDir($expected);

		$msg = 'Wrong NativeAdapter::setTemplateDir property value!';
		$this->assertAttributeEquals(
			$expected, 'template_dir', 'Veles\View\Adapters\NativeAdapter', $msg
		);
	}

	/**
	 * @covers Veles\View\Adapters\NativeAdapter::getTemplateDir
	 * @depends testSetTemplateDir
	 */
	public function testGetTemplateDir()
	{
		$expected = '/templates/dir';
		NativeAdapter::setTemplateDir($expected);

		$result = NativeAdapter::getTemplateDir();

		$msg = 'Wrong NativeAdapter::getTemplateDir() result!';
		$this->assertSame($expected, $result, $msg);
	}

	/**
	 * @covers Veles\View\Adapters\NativeAdapter::show
	 * @todo   Implement testShow().
	 */
	public function testShow()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Veles\View\Adapters\NativeAdapter::get
	 * @todo   Implement testGet().
	 */
	public function testGet()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Veles\View\Adapters\NativeAdapter::isCached
	 * @todo   Implement testIsCached().
	 */
	public function testIsCached()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}
}
