<?php
namespace Tests\View\Adapters;

use Veles\View\Adapters\ViewAdapterAbstract;
use Veles\View\Adapters\NativeAdapter;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-12-19 at 11:42:12.
 * @group View
 */
class ViewAdapterAbstractTest extends \PHPUnit_Framework_TestCase
{
	/**
	 * @var ViewAdapterAbstract
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp()
	{
		$this->object = new NativeAdapter;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown()
	{
	}

	/**
	 * @covers Veles\View\Adapters\ViewAdapterAbstract::instance
	 * @todo   Implement testInstance().
	 */
	public function testInstance()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Veles\View\Adapters\ViewAdapterAbstract::getDriver
	 * @todo   Implement testGetDriver().
	 */
	public function testGetDriver()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Veles\View\Adapters\ViewAdapterAbstract::setDriver
	 * @todo   Implement testSetDriver().
	 */
	public function testSetDriver()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Veles\View\Adapters\ViewAdapterAbstract::__call
	 * @todo   Implement test__call().
	 */
	public function test__call()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Veles\View\Adapters\ViewAdapterAbstract::set
	 * @todo   Implement testSet().
	 */
	public function testSet()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Veles\View\Adapters\ViewAdapterAbstract::del
	 * @todo   Implement testDel().
	 */
	public function testDel()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}
}
