<?if (1 === $first_link) {?>
	<a href="/page-1.html">&laquo;</a>
<?}
while ($index <= $page_nums) {
	if ($index === $curr_page) {
		if ($index > 1) {?>
			<span class="curr pager-margin"><?=$index?></span>
		<?} else {?>
			<span class="curr"><?=$index?></span>
		<?}?>
	<?} elseif ($index > 1) {?>
		<a href="/page-<?=$index?>.html" class="pager-margin"><?=$index?></a>
	<?} else {?>
		<a href="/page-<?=$index?>.html"><?=$index?></a>
	<?}
	++$index;
}
if ($last_link) {?>
	<a href="/page-<?=$last_link?>.html" class="pager-margin">&raquo;</a>
<?}?>
