<?php
namespace Veles\Tests\ErrorHandler;

use Veles\ErrorHandler\BaseErrorHandler;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-08-11 at 19:33:00.
 * @group ErrorHandler
 */
class BaseErrorHandlerTest extends \PHPUnit_Framework_TestCase
{
	/**
	 * @var BaseErrorHandler
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp()
	{
		$this->object = new BaseErrorHandler;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown()
	{
	}

	/**
	 * @covers Veles\ErrorHandler\BaseErrorHandler::getVars
	 */
	public function testGetVars()
	{
		$expected = [];
		$result = $this->object->getVars();

		$msg = 'BaseErrorHandler::getVars() returns wrong result!';
		$this->assertSame($expected, $result, $msg);

		$msg = 'BaseErrorHandler::vars has wrong default type!';
		$this->assertAttributeInternalType('array', 'vars', $this->object, $msg);
	}
}
