<?php
namespace Veles\Tests\ErrorHandler\HtmlBuilders;

use Veles\ErrorHandler\FatalErrorHandler;
use Veles\ErrorHandler\HtmlBuilders\ErrorBuilder;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-11-06 at 08:29:58.
 * @group error-handler
 */
class AbstractBuilderTest extends \PHPUnit_Framework_TestCase
{
	/**
	 * @var ErrorBuilder
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp()
	{
        $this->object = new ErrorBuilder;
	}

	/**
	 * @covers Veles\ErrorHandler\HtmlBuilders\AbstractBuilder::setHandler
	 */
	public function testSetHandler()
	{
		$expected = new FatalErrorHandler;
		$this->object->setHandler($expected);
		$msg = 'AbstractBuilder::setHandler() wrong behavior!';
		$this->assertAttributeSame($expected, 'handler', $this->object, $msg);
	}

	/**
	 * @covers Veles\ErrorHandler\HtmlBuilders\AbstractBuilder::setTemplate
	 */
	public function testSetTemplate()
	{
		$expected = uniqid();
		$this->object->setTemplate($expected);
		$msg = 'AbstractBuilder::setTemplate() wrong behavior!';
		$this->assertAttributeSame($expected, 'template', $this->object, $msg);
	}

	/**
	 * @covers Veles\ErrorHandler\HtmlBuilders\AbstractBuilder::getTemplate
	 * @depends testSetTemplate
	 */
	public function testGetTemplate()
	{
		$expected = uniqid();
		$this->object->setTemplate($expected);
		$result = $this->object->getTemplate();
		$msg = 'AbstractBuilder::setTemplate() wrong behavior!';
		$this->assertSame($expected, $result, $msg);
	}
}
