<?php
namespace Veles\ErrorHandler\HtmlBuilders;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-11-06 at 08:29:58.
 */
class AbstractBuilderTest extends \PHPUnit_Framework_TestCase
{
	/**
	 * @var AbstractBuilder
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp()
	{
//        $this->object = new AbstractBuilder;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown()
	{
	}

	/**
	 * @covers Veles\ErrorHandler\HtmlBuilders\AbstractBuilder::setHandler
	 * @todo   Implement testSetHandler().
	 */
	public function testSetHandler()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Veles\ErrorHandler\HtmlBuilders\AbstractBuilder::getTemplate
	 * @todo   Implement testGetTemplate().
	 */
	public function testGetTemplate()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Veles\ErrorHandler\HtmlBuilders\AbstractBuilder::setTemplate
	 * @todo   Implement testSetTemplate().
	 */
	public function testSetTemplate()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}
}
