<?php
namespace Veles\ErrorHandler\HtmlBuilders;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-11-06 at 08:29:36.
 */
class ErrorBuilderTest extends \PHPUnit_Framework_TestCase
{
	/**
	 * @var ErrorBuilder
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp()
	{
		$this->object = new ErrorBuilder;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown()
	{
	}

	/**
	 * @covers Veles\ErrorHandler\HtmlBuilders\ErrorBuilder::getHtml
	 * @todo   Implement testGetHtml().
	 */
	public function testGetHtml()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}
}
