<?php
namespace Veles\ErrorHandler\Subscribers;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-11-06 at 08:21:33.
 */
class EmailNotifierTest extends \PHPUnit_Framework_TestCase
{
	/**
	 * @var EmailNotifier
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp()
	{
		$this->object = new EmailNotifier;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown()
	{
	}

	/**
	 * @covers Veles\ErrorHandler\Subscribers\EmailNotifier::update
	 * @todo   Implement testUpdate().
	 */
	public function testUpdate()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Veles\ErrorHandler\Subscribers\EmailNotifier::getMessageBuilder
	 * @todo   Implement testGetMessageBuilder().
	 */
	public function testGetMessageBuilder()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Veles\ErrorHandler\Subscribers\EmailNotifier::setMessageBuilder
	 * @todo   Implement testSetMessageBuilder().
	 */
	public function testSetMessageBuilder()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Veles\ErrorHandler\Subscribers\EmailNotifier::init
	 * @todo   Implement testInit().
	 */
	public function testInit()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Veles\ErrorHandler\Subscribers\EmailNotifier::addHeaders
	 * @todo   Implement testAddHeaders().
	 */
	public function testAddHeaders()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}
}
