<?php
namespace Veles\ErrorHandler\Subscribers;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-11-06 at 08:25:43.
 */
class ErrorRendererTest extends \PHPUnit_Framework_TestCase
{
	/**
	 * @var ErrorRenderer
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp()
	{
		$this->object = new ErrorRenderer;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown()
	{
	}

	/**
	 * @covers Veles\ErrorHandler\Subscribers\ErrorRenderer::update
	 * @todo   Implement testUpdate().
	 */
	public function testUpdate()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Veles\ErrorHandler\Subscribers\ErrorRenderer::getMessageBuilder
	 * @todo   Implement testGetMessageBuilder().
	 */
	public function testGetMessageBuilder()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Veles\ErrorHandler\Subscribers\ErrorRenderer::setMessageBuilder
	 * @todo   Implement testSetMessageBuilder().
	 */
	public function testSetMessageBuilder()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}
}
