<?php
namespace Veles\Tests\Model;

use Veles\Model\ActiveRecord;
use Veles\DataBase\Db;
use Veles\DataBase\Adapters\PdoAdapter;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-12-27 at 16:16:41.
 */
class ActiveRecordTest extends \PHPUnit_Framework_TestCase
{
	/**
	 * @var ActiveRecord
	 */
	protected $object;
	protected static $tbl_name;

	public static function setUpBeforeClass()
	{
		// Create test table
		$tbl_name = static::$tbl_name = News::TBL_NAME;

		Db::setAdapter(PdoAdapter::instance());
		Db::query("
			CREATE TABLE IF NOT EXISTS $tbl_name (
			  id int(10) unsigned NOT NULL AUTO_INCREMENT,
			  title char(30) NOT NULL,
			  content char(60) NOT NULL,
			  author char(30) NOT NULL,
			  PRIMARY KEY (id)
			) ENGINE=INNODB DEFAULT CHARSET=utf8
		");
		for ($i = 1; $i < 21; ++$i) {
			Db::query("
				INSERT INTO $tbl_name
					(id, title, content, author)
				VALUES
					(?, ?, ?, ?)
			", [$i, "title_$i", "content_$i", "author_$i"], 'isss');
		}
	}

	public static function tearDownAfterClass()
	{
		$table =& static::$tbl_name;
		Db::query("DROP TABLE $table");
	}

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp()
	{
		$this->object = new ActiveRecord;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown()
	{
	}

	/**
	 * @covers Veles\Model\ActiveRecord::getMap
	 */
	public function testGetMap()
	{
		$news = new News;
		$expected = [
			'id'      => 'int',
			'title'   => 'string',
			'content' => 'string',
			'author'  => 'string'
		];
		$result = $news->getMap();
		$msg = 'ActiveRecord::getMap() returns wrong result!';
		$this->assertSame($expected, $result, $msg);
	}

	/**
	 * @covers Veles\Model\ActiveRecord::getById
	 * @dataProvider getByIdProvider
	 */
	public function testGetById($id, $expected)
	{
		$news = new News;
		$result = $news->getById($id);
		$msg = 'ActiveRecords::getById() returns wrong result!';
		$this->assertSame($expected, $result, $msg);

		$result = ['id' => '', 'title' => '', 'content' => '', 'author' => ''];
		$expected = ($expected)
			? [
				'id'      => "$id",
				'title'   => "title_$id",
				'content' => "content_$id",
				'author'  => "author_$id"
			]
			: $result;

		$news->getProperties($result);
		$msg = 'Wrong ActiveRecords::getById() behavior!';
		$this->assertSame($expected, $result, $msg);
	}

	public function getByIdProvider()
	{
		return [
			[3, true],
			[0, false],
			[500, false],
			[20, true]
		];
	}

	/**
	 * @covers Veles\Model\ActiveRecord::getAll
	 * @todo   Implement testGetAll().
	 */
	public function testGetAll()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Veles\Model\ActiveRecord::save
	 * @todo   Implement testSave().
	 */
	public function testSave()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Veles\Model\ActiveRecord::delete
	 * @todo   Implement testDelete().
	 */
	public function testDelete()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Veles\Model\ActiveRecord::setProperties
	 * @todo   Implement testSetProperties().
	 */
	public function testSetProperties()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Veles\Model\ActiveRecord::getProperties
	 * @todo   Implement testGetProperties().
	 */
	public function testGetProperties()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Veles\Model\ActiveRecord::find
	 * @todo   Implement testFind().
	 */
	public function testFind()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Veles\Model\ActiveRecord::setBuilder
	 * @todo   Implement testSetBuilder().
	 */
	public function testSetBuilder()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}
}
