<?php
namespace Veles\Tests\Model;

use Veles\Model\QueryBuilder;
use Veles\Model\User;
use Veles\Auth\UsrGroup;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-12-27 at 16:15:58.
 */
class QueryBuilderTest extends \PHPUnit_Framework_TestCase
{
	/**
	 * @var QueryBuilder
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp()
	{
		$this->object = new QueryBuilder;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown()
	{
	}

	/**
	 * @covers Veles\Model\QueryBuilder::insert
	 */
	public function testInsert()
	{
		$group = UsrGroup::GUEST;
		$hash = md5('lalala');

		$user = new User;
		$user->id = 1;
		$user->email = 'mail@mail.org';
		$user->hash = $hash;
		$user->group = $group;

		$expected = "
			INSERT
				`users`
				(`id`, `email`, `hash`, `group`)
			VALUES
				(1, 'mail@mail.org', '$hash', $group)
		";
		$result = $this->object->insert($user);

		$msg = 'QueryBuilder::insert() returns wrong result!';
		$this->assertSame($expected, $result, $msg);
	}

	/**
	 * @covers Veles\Model\QueryBuilder::update
	 * @todo   Implement testUpdate().
	 */
	public function testUpdate()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Veles\Model\QueryBuilder::getById
	 * @todo   Implement testGetById().
	 */
	public function testGetById()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Veles\Model\QueryBuilder::delete
	 * @todo   Implement testDelete().
	 */
	public function testDelete()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Veles\Model\QueryBuilder::find
	 * @todo   Implement testFind().
	 */
	public function testFind()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Veles\Model\QueryBuilder::setPage
	 * @todo   Implement testSetPage().
	 */
	public function testSetPage()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}
}
