<?php
/**
 * Unit-test for View class
 * @file    ViewTest.php
 *
 * PHP version 5.3.9+
 *
 * @author  Alexander Yancharuk <alex@itvault.info>
 * @date    Вск Янв 20 18:40:31 2013
 * @copyright The BSD 3-Clause License.
 */

namespace Veles\Tests\View;

use PHPUnit_Framework_TestCase;
use ReflectionObject;
use Veles\View\Adapters\NativeAdapter;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-01-20 at 18:39:47.
 */
class ViewTest extends PHPUnit_Framework_TestCase
{
	/**
	 * Container for View object
	 * @var View
	 */
	protected $object;

	/**
	 * File name of template
	 * @var string
	 */
	protected $tpl;

	/**
	 * Final HTML output
	 * @var string
	 */
	protected $html;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp()
	{
		$this->object = new View;
		$this->tpl = 'Frontend/index.phtml';

		$this->html = <<<EOF
<!DOCTYPE html>
<html>
<head>
	<title>Veles is a fast PHP framework</title>
</head>
<body>
	<div id="main_wrapper">
		Test complete!
	</div>
	<div id="footer_wrapper">
		Hello World!
	</div>
</body>
</html>

EOF;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown()
	{
	}

	/**
	 * Unit-test for View::setAdapter
	 * @covers Veles\View\View::setAdapter
	 * @see Veles\View\View::setAdapter
	 */
	public function testSetAdapter()
	{
		View::unsetAdapter();
		$adapter = NativeAdapter::instance();
		View::setAdapter($adapter);

		$msg = 'Wrong setAdapter behavior!';
		$this->assertAttributeEquals(
			$adapter,
			'adapter',
			'\Veles\View\View',
			$msg
		);
	}

	/**
	 * Unit-test for View::getAdapter
	 * @covers Veles\View\View::getAdapter
	 * @see Veles\View\View::getAdapter
	 */
	public function testGetAdapter()
	{
		View::unsetAdapter();
		$expected = NativeAdapter::instance();
		$_SERVER['REQUEST_URI'] = 'index.html';

		$result = View::getAdapter();
		$msg = 'Wrong View::getAdapter() result';
		$this->assertSame($expected, $result, $msg);

		$expected = NativeAdapter::instance();
		View::unsetAdapter();
		View::setAdapter($expected);

		$result = View::getAdapter();

		$this->assertSame($expected, $result, $msg);
	}

	/**
	 * Unit-test for View::set
	 * @covers Veles\View\View::set
	 * @dataProvider setProvider
	 * @see Veles\View\View::set
	 */
	public function testSet($vars)
	{
		$this->object->set($vars);

		$this->expectOutputString($this->html);

		$this->object->show($this->tpl);
	}

	/**
	 * DataProvider for View::set
	 */
	public function setProvider()
	{
		return array(
			array(
				array('a' => 'Test', 'b' => 'complete', 'c' => 'Hello')
			)
		);
	}

	/**
	 * Unit-test for View::del
	 * @covers Veles\View\View::del
	 * @dataProvider delProvider
	 * @see Veles\View\View::del
	 */
	public function testDel($vars, $del, $expected)
	{
		View::set($vars);
		View::del($del);

		$object = new ReflectionObject(View::getAdapter());

		$prop = $object->getProperty('variables');
		$prop->setAccessible(true);
		$result = $prop->getValue();
		$msg = 'Wrong View::del() behavior!';

		foreach ($expected as $var => $value) {
			$this->assertSame($value, isset($result[$var]), $msg);
		}
	}

	/**
	 * DataProvider for View::del
	 */
	public function delProvider()
	{
		return array(
			array(
				array('variable-1' => 'string', 'variable-2' => 'string'),
				array('variable-1'),
				array('variable-1' => false, 'variable-2' => true)
			),
			array(
				array('variable-3' => 'string', 'variable-4' => 'string'),
				array('variable-4'),
				array('variable-3' => true, 'variable-4' => false)
			)
		);
	}

	/**
	 * Unit-test for View::isCached
	 * @covers Veles\View\View::isCached
	 * @depends testGetAdapter
	 * @see Veles\View\View::isCached
	 */
	public function testIsCached()
	{
		$adapter = View::getAdapter();
		$tpl = $adapter->getTemplateDir();

		$expected = $adapter->isCached($tpl);
		$result = View::isCached($tpl);

		$msg = 'Wrong View::isCached() result!';
		$this->assertSame($expected, $result, $msg);
	}

	/**
	 * Unit-test for View::show
	 * @covers Veles\View\View::show
	 * @depends testSet
	 * @see Veles\View\View::show
	 */
	public function testShow()
	{
		$this->expectOutputString($this->html);

		$this->object->show($this->tpl);
	}

	/**
	 * Unit-test for View::get
	 * @covers Veles\View\View::get
	 * @depends testSet
	 * @see Veles\View\View::get
	 */
	public function testGet()
	{
		$expected =& $this->html;

		$result = $this->object->get($this->tpl);

		$msg = 'Wrong result type: ' . gettype($result);
		$this->assertInternalType('string', $result, $msg);

		$msg = 'Wrong content of HTML in View::get()';
		$this->assertSame($expected, $result, $msg);
	}
}
