<?php
namespace Veles\Tests\Routing;

use Veles\Routing\IniConfigLoader;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-05-24 at 17:39:24.
 * @group route
 */
class IniConfigLoaderTest extends \PHPUnit_Framework_TestCase
{
	/**
	 * @var IniConfigLoader
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp()
	{
		$this->object = new IniConfigLoader(TEST_DIR . '/Project/routes.ini');
	}

	/**
	 * @covers Veles\Routing\IniConfigLoader::load
	 * @covers Veles\Routing\IniConfigLoader::buildTree
	 */
	public function testLoad()
	{
		$expected = [
			'Home'     =>
				[
					'class'      => 'Veles\Routing\RouteRegex',
					'view'       => 'Veles\View\Adapters\NativeAdapter',
					'route'      => '#^\/(?:index.html|page\-(?<page>\d+)\.html)?$#',
					'tpl'        => 'Frontend/index.phtml',
					'controller' => 'Frontend\Home',
					'action'     => 'index'
				],
			'TestMap'  =>
				[
					'class'      => 'Veles\Routing\RouteRegex',
					'view'       => 'Veles\View\Adapters\NativeAdapter',
					'route'      => '#^\/book\/(?<book_id>\d+)\/user\/(?<user_id>\d+)$#',
					'tpl'        => 'Frontend/index.phtml',
					'controller' => 'Frontend\Home',
					'action'     => 'book'
				],
			'Contacts' =>
				[
					'class'      => 'Veles\Routing\RouteStatic',
					'route'      => '/contacts',
					'controller' => 'Frontend\Contacts',
					'action'     => 'getAddress',
					'ajax'       => '1',
				],
			'User'     =>
				[
					'class' => 'Veles\\Routing\\RouteStatic',
					'route' => '/user',
				],
		];

		$result = $this->object->load();

		$msg = 'IniConfigLoader::load() returns wrong result!';
		$this->assertSame($expected, $result, $msg);
	}
}
