<?php
namespace Veles\Tests\Routing;

use Veles\Routing\PhpConfigLoader;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-05-24 at 18:10:59.
 */
class PhpConfigLoaderTest extends \PHPUnit_Framework_TestCase
{
	/**
	 * @var PhpConfigLoader
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp()
	{
		$this->object = new PhpConfigLoader(TEST_DIR . '/Project/routes.php');
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown()
	{
	}

	/**
	 * @covers Veles\Routing\PhpConfigLoader::load
	 * @todo   Implement testLoad().
	 */
	public function testLoad()
	{
		$expected = include TEST_DIR . '/Project/routes.php';
		$result = $this->object->load();

		$msg = 'PhpConfigLoader::load() returns wrong result!';
		$this->assertSame($expected, $result, $msg);
	}
}
