<?php
namespace Tests\Routing;

use Veles\Routing\RouteStatic;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-12-23 at 06:58:58.
 */
class RouteStaticTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var RouteStatic
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new RouteStatic;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Veles\Routing\RouteStatic::check
     * @todo   Implement testCheck().
     */
    public function testCheck()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
