<?php
namespace Tests\Routing;

use Veles\Routing\Route;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-12-22 at 09:52:48.
 */
class RouteTest extends \PHPUnit_Framework_TestCase
{
	/**
	 * @var Route
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp()
	{
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown()
	{
	}

	/**
	 * @covers Veles\Routing\Route::isAjax
	 * @todo   Implement testIsAjax().
	 */
	public function testIsAjax()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Veles\Routing\Route::instance
	 * @todo   Implement testInstance().
	 */
	public function testInstance()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Veles\Routing\Route::getController
	 * @todo   Implement testGetController().
	 */
	public function testGetController()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Veles\Routing\Route::getActionName
	 * @todo   Implement testGetActionName().
	 */
	public function testGetActionName()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Veles\Routing\Route::getAdapter
	 * @todo   Implement testGetAdapter().
	 */
	public function testGetAdapter()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Veles\Routing\Route::getPageName
	 * @todo   Implement testGetPageName().
	 */
	public function testGetPageName()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Veles\Routing\Route::getMap
	 * @todo   Implement testGetMap().
	 */
	public function testGetMap()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Veles\Routing\Route::getTemplate
	 * @todo   Implement testGetTemplate().
	 */
	public function testGetTemplate()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}
}
