<?php
namespace Tests\Routing;

use Veles\Tests\Routing\RouteRegexChild;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-12-21 at 18:06:33.
 */
class RouteRegexTest extends \PHPUnit_Framework_TestCase
{
	/**
	 * @var RouteRegex
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp()
	{
		$this->object = new RouteRegexChild;
		$this->object->setMap(null);
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown()
	{
	}

	/**
	 * @covers Veles\Routing\RouteRegex::check
	 * @dataProvider testCheckProvider
	 */
	public function testCheck($pattern, $url, $expected, $maps)
	{
		$result = $this->object->check($pattern, $url);
		$msg = 'Wrong RouteRegex::check() behavior!';
		$this->assertSame($expected, $result, $msg);

		$msg = 'RouteReges doesn\'t match url params!';
		$this->assertAttributeSame($maps, 'map', $this->object, $msg);
	}

	public function testCheckProvider()
	{
		return [
			['#^\/article\/([\d\w\-]+).html$#', '/article/234.html', true, [1 => '234']],
			['#^\/article\/([\d\w\-]+).html$#', '/article/lal-4.html', true, [1 => 'lal-4']],
			['#^\/article\/([\d\w\-]+).html$#', '/article/html', false, null],
			['#^\/article\/([\d\w\-]+).html$#', 'index.html', false, null],
			['#^\/article\/([\d\w\-]+).html$#', '/article/lal 4.html', false, null]
		];
	}

	/**
	 * @covers Veles\Routing\RouteRegex::getMap
	 * @todo   Implement testGetMap().
	 */
	public function testGetMap()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}
}
