<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
    <title><?=$title?></title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <link href="/css/style.css" type="text/css" rel="stylesheet">
    <meta content="ru" http-equiv="content-language">
    <meta content="text/html; charset=utf-8" http-equiv="content-type">
    <meta content="index,all" name="robots">
    <meta content="5 days" name="revisit">
    <meta content="5 days" name="revisit-after">
    <meta content="php framework veles" name="Keywords">
    <meta content="Veles - PHP micro-framework" name="Description">
</head>
