<?php
namespace Veles\Tests\Helpers;

use Veles\DataBase\Loggers\PdoErrorLogger;
use Veles\Helpers\Observable;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-12-19 at 18:41:12.
 * @group helpers
 */
class ObservableTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Observable
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Observable;
    }

    /**
     * @covers Veles\Helpers\Observable::attach
     */
    public function testAttach()
    {
		$msg = 'Wrong initial value of Observable::attach';
		$this->assertAttributeSame(array(), 'observers', $this->object, $msg);

		$obj = new PdoErrorLogger;
		$this->object->attach($obj);
		$expected = array($obj);

		$msg = 'Wrong behavior of Observable::attach';
		$this->assertAttributeSame($expected, 'observers', $this->object, $msg);
    }

    /**
     * @covers Veles\Helpers\Observable::detach
	 * @depends testAttach
     */
    public function testDetach()
    {
		$obj = new PdoErrorLogger;
		$this->object->attach($obj);

		$expected = array();
		$this->object->detach($obj);
		$msg = 'Wrong behavior of Observable::detach';
		$this->assertAttributeSame($expected, 'observers', $this->object, $msg);
    }

    /**
     * @covers Veles\Helpers\Observable::notify
	 * @depends testAttach
     */
    public function testNotify()
    {
		$obj = new ClassForTesting;

		$this->object->attach($obj);

		$this->object->notify();

		$msg = 'Wrong behavior of Observable::notify';
		$this->assertAttributeSame(true, 'flag', $obj, $msg);
    }
}
